### ISSUE TITLE
The formatter doesn't work if the file contains a lambda

### ISSUE THREAD

**Issue by hatemsh** [EddieDover/vscode-formatter-godot#15]
Just like the title says, any file that contains a lambda throws an `Unexpected token Token` and refuses to format. If I remove all the lambdas it works.
<img width="796" alt="image" src="https://github.com/user-attachments/assets/2d0e6533-027d-4e5d-9a1d-7cc3a731da8f" />

I'm using the extension on Mac Sequoia 15.0.1
VSCode Version: 1.96.2

**Comment by EddieDover** [comment]
What version of gdtoolkit do you have installed?  There's a chance you may need to update to gdtoolkit4.X with
``pip install "gdtoolkit==4.*"`` or your equivalent command depending on package manager preference.

When testing this, I ran into the problem until I updated to the newest gdtoolkit and now I am unable to replicate.

**Comment by EddieDover** [comment]
> What version of gdtoolkit do you have installed? There's a chance you may need to update to gdtoolkit4.X with `pip install "gdtoolkit==4.*"` or your equivalent command depending on package manager preference.
> 
> When testing this, I ran into the problem until I updated to the newest gdtoolkit and now I am unable to replicate.
> 
> My environment is a bit unstable due to some other development I'm doing, so it may still be an issue I'm just not seeing. Will continue to strip my env back down to base levels so I can test.

I also want to note that I had an hiccup with gdtoolkit after the update to 4.* where one of it's dependencies was having an issue so I had to force a reinstall with ``py -m pip install --upgrade --force-reinstall gdtoolkit``  See [here](https://github.com/Scony/godot-gdscript-toolkit/issues/341)

**Comment by hatemsh** [comment]
I had version `4.1.0` 
I deleted the old version and then used the `install "gdtoolkit==4.*"` and now it works

**Comment by EddieDover** [comment]
Glad it's working. Closing the issue. Happy Development!
