### ISSUE TITLE
Maximum number of characters per line for the formatter is ignored

### ISSUE THREAD

**Issue by juan-medina** [EddieDover/vscode-formatter-godot#16]
Does no matter what you set in the setting, it will always check 100 characters.

![image](https://github.com/user-attachments/assets/8c0e2360-6793-4d54-a3d4-59e6702eeb6b)

![image](https://github.com/user-attachments/assets/cfef099f-bd56-4257-9206-6e72752e1194)

**Comment by EddieDover** [comment]
See my reply to the issue here:

https://github.com/EddieDover/vscode-formatter-godot/issues/12

**Comment by juan-medina** [comment]
I see I indeed solve creating a *.gdlintrc* file

```
max-line-length: 150
```

I understand is going to be not possible just to do it in the extension, will close the issue, thank you
