### ISSUE TITLE
gdlintrc config file is ignored

### ISSUE THREAD

**Issue by VaustXIII** [EddieDover/vscode-formatter-godot#5]
Hello!

It seems that this extension doesn't take into account the gdlintrc config file.
For example I get `function-variable-name` gdlint error both with the extension and when running gdlint in the command line. Then I dump the config file with `gdlint -d` command and change the gdlintrc file. Now gdlint in the command line passes because a variable name is ok with new config, but the extension still gives me an error.

**Comment by freysie** [comment]
I’m seeing the same issue. Confusingly, I’m pretty sure it worked in the past, but no longer.

**Comment by EddieDover** [comment]
Sorry to say I never got an alert for this issue being opened. That being said, I'm pretty sure the functionality from this extension is going to get rolled into the 'unofficial official' plugin from https://github.com/Scony/godot-gdscript-toolkit, I'm just not sure when. (See https://github.com/Scony/godot-gdscript-toolkit/issues/232)

If this is still something you'd like me to look at, I'd be happy to, just drop a ping here.

**Comment by VaustXIII** [comment]
Thanks for the answer. Yeah if it's gonna be a part of the gdscript toolkit extension, then there's probably no point in duplicating the work. Feel free to close the request.
Cheers

**Comment by kuhnchris** [comment]
> Sorry to say I never got an alert for this issue being opened. That being said, I'm pretty sure the functionality from this extension is going to get rolled into the 'unofficial official' extension from https://github.com/Scony/godot-gdscript-toolkit, I'm just not sure when. (See [Scony/godot-gdscript-toolkit#232](https://github.com/Scony/godot-gdscript-toolkit/issues/232))
> 
> If this is still something you'd like me to look at, I'd be happy to, just drop a ping here.

I think the project settings / repo settings still have me as "primary contact" since I got some mails regarding that but I didn't think you didn't get them aswell, sorry.
And yes, if it his getting rolled into Scony's extension that would probabbly make life easier we the community wouldn't have to maintain 2 different project and sources. 👍

**Comment by chrisl8** [comment]
This issue should be fixed now.

**Comment by EddieDover** [comment]
Forgot it won't close unless I tagged this in the merge.
